---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

# Controls when the action will run. Workflow runs when manually triggered
# using the UI or API.
'on':
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Check out tmpl.vim
        uses: actions/checkout@v3
        with:
          path: tmpl.vim

      - name: Fetch vader
        uses: actions/checkout@v3
        with:
          repository: junegunn/vader.vim
          path: vader.vim

      - name: Install dependencies
        run: sudo apt install -y neovim vim-nox

      - name: Test with vim
        run: VIM_BIN=vim ./tmpl.vim/tests/run_tests.sh

      - name: Test with neovim
        run: VIM_BIN=nvim ./tmpl.vim/tests/run_tests.sh
